name: synchronize main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v2

      - uses: ZetabotCo/github-repository-sync-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          target_repo_url: git@gitlab.impstudio.id:zetabot/blog.git
          source_branch: main
          destination_branch: main